#Database
MYSQL_USERNAME: root
MYSQL_PASSWORD:
MYSQL_DATABASE: gamebox
MYSQL_HOST: localhost
MYSQL_PORT: 3306

JWT_SECRET: Nf73!zV@qLpWm2#Xe4Rg9^TbK8Ay1Cd$

#Email
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_USERNAME: no.reply.gamebox.mail@gmail.com
EMAIL_PASSWORD: upag micg cfou fval
VERIFY_EMAIL_HOST: http://localhost:8080

OLD_STEAM_API_KEY: 53A3706971FCED8E39A21982B2517DF0

STEAM_API_KEY: 9F8695D275866EEF5362E0444055DED9

RAWG_API_KEY: c4218b73cc934a40b385b72d9c84647b